apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "GeoLocationEcho.fullname" . }}-redeployer
spec:
  schedule: "30 18 * * 2"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: redeployer
            image: {{ .Values.redeployerImage.repository }}:{{ .Values.redeployerImage.tag }}
            imagePullPolicy: IfNotPresent
            env:
              - name: GEOIP_PRODUCT_IDS
                value: {{ .Values.geoip_account.product_ids }}
              - name: DEPLOYMENT
                value: {{ include "GeoLocationEcho.fullname" . }}
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            envFrom:
            - secretRef:
                name: geoip-account-secrets
          restartPolicy: OnFailure
