apiVersion: v1
kind: Secret
metadata:
  name: geoip-account-secrets
  labels:
{{ include "GeoLocationEcho.labels" . | indent 4 }}
data:
  GEOIP_ACCOUNT_ID: {{ .Values.geoip_account.id | b64enc | quote }}
  GEOIP_LICENSE_KEY: {{ .Values.geoip_account.licenseKey | b64enc | quote }}